Name change
traitecoevo/hmDE pull request #27
Opened 2024-07-29 10:05 UTC by Tess-LaCoil

Updated name to hmDE - hierarchical methods for DEs - from rmot as 'repeat measures' is already a thing in statistics.

2024-07-29 10:13 UTC, dfalster commented
Looks promising. One thought - will it be annoying to have a name mixing caps and lowercase? Thinking as a user, it would be easier if functions names didn't include case change. WDYT?

2024-07-29 10:21 UTC, Tess-LaCoil commented
I'm ambivilent on the matter. If you'd prefer all lower/upper say which and I'll make the changes.

2024-07-29 10:27 UTC, dfalster commented
Thoughts @fontikar ?

2024-07-30 01:19 UTC, fontikar commented
I'm a big fan of snake_case rather than camelCase, easier to type as @dfalster mentioned. Not the biggest fan of a combo of snake and camel 

e.g. Found in NAMESPACE of function names.

```
export(hmDE_assign_data)
export(hmDE_model)
export(hmDE_run)
```

is `hmde` a better alternative?

2024-07-30 01:20 UTC, fontikar commented
Tests failing because of the new data objects: 

```
❯ checking for missing documentation entries ... WARNING
  Undocumented code objects:
    ‘hmDE_assign_data’ ‘hmDE_model’ ‘hmDE_run’ ‘Lizard_Mass_Data’
    ‘Small_Tree_Size_Data’ ‘Tree_Size_Data’ ‘Trout_Size_Data’
  Undocumented data sets:
    ‘Lizard_Mass_Data’ ‘Small_Tree_Size_Data’ ‘Tree_Size_Data’
    ‘Trout_Size_Data’
  All user-level objects in a package should have documentation entries.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
  ```
  
  Are these internal testing data or data the user can access to take the package for a spin.
  
  See here on how to document: https://r-pkgs.org/data.html

2024-07-30 03:30 UTC, Tess-LaCoil commented
Okay, sounds like hmde is the go. I'll implement it when I'm home from Wollongong.

2024-07-30 08:41 UTC, dfalster requested changes
Name looks good, but lost package title and version number. Please update

2024-07-30 08:41 UTC, dfalster commented on DESCRIPTION
>  Title: What the Package Does (One Line, Title Case)
Missing a title and need to update version number

2024-07-30 08:53 UTC, dfalster approved these changes

2024-07-30 09:14 UTC, merged